export interface PokemonItem {
  id: string;
  dexNumber: number;
  nameTh: string;
  nameEn: string;
  typeId: string;
  height: string;
  weight: string;
  ability: string;
  description: string;
  imageUrl: string;
}

export interface PokemonType {
  id: string;
  nameTh: string;
  nameEn: string;
  icon: string;
  colorClass: string;
  bgClass: string;
  badgeClass: string;
  pokemon: PokemonItem[];
}

export const POKEMON_TYPES: PokemonType[] = [
  {
    id: "fire",
    nameTh: "ไฟ",
    nameEn: "Fire",
    icon: "🔥",
    colorClass: "text-amber-500",
    bgClass: "bg-amber-600/20 border-amber-500/40 text-amber-300",
    badgeClass: "bg-amber-600 text-white",
    pokemon: [
      {
        id: "charmander",
        dexNumber: 4,
        nameTh: "ฮิโตคาเงะ",
        nameEn: "Charmander",
        typeId: "fire",
        height: "0.6 m",
        weight: "8.5 kg",
        ability: "Blaze (ไฟลุกโชน)",
        description: "เปลวไฟที่ปลายหางจะบ่งบอกถึงสภาพอารมณ์และพลังชีวิตของฮิโตคาเงะ หากเปลวไฟดับลงจะถือว่าตกอยู่ในอันตราย",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
      },
      {
        id: "charmeleon",
        dexNumber: 5,
        nameTh: "ลิซาร์โดะ",
        nameEn: "Charmeleon",
        typeId: "fire",
        height: "1.1 m",
        weight: "19.0 kg",
        ability: "Blaze (ไฟลุกโชน)",
        description: "มีนิสัยดุร้าย ชอบต่อสู้อย่างไม่เกรงกลัว เมื่อตื่นเต้นเปลวไฟสีฟ้าแกมขาวจะพวยพุ่งออกจากปลายหาง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png",
      },
      {
        id: "charizard",
        dexNumber: 6,
        nameTh: "ลิซาร์ดอน",
        nameEn: "Charizard",
        typeId: "fire",
        height: "1.7 m",
        weight: "90.5 kg",
        ability: "Blaze (ไฟลุกโชน)",
        description: "บินท่องไปทั่วท้องฟ้าเพื่อค้นหาคู่ต่อสู้ที่แข็งแกร่ง พ่นเปลวเพลิงความร้อนสูงจนสามารถละลายก้อนหินได้",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png",
      },
      {
        id: "cyndaquil",
        dexNumber: 155,
        nameTh: "ฮิโนอาราชิ",
        nameEn: "Cyndaquil",
        typeId: "fire",
        height: "0.5 m",
        weight: "7.9 kg",
        ability: "Blaze (ไฟลุกโชน)",
        description: "มีนิสัยขี้อายและชอบขดตัวเป็นก้อนกลม เมื่อตกใจจะปล่อยเปลวไฟร้อนแรงออกมาจากแผ่นหลัง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/155.png",
      },
      {
        id: "quilava",
        dexNumber: 156,
        nameTh: "แม็กมาราชิ",
        nameEn: "Quilava",
        typeId: "fire",
        height: "0.9 m",
        weight: "19.0 kg",
        ability: "Blaze (ไฟลุกโชน)",
        description: "ปกคลุมด้วยขนที่ไม่ติดไฟ สามารถปล่อยระเบิดเปลวไฟก่อนการโจมตีได้อย่างรวดเร็ว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/156.png",
      },
      {
        id: "typhlosion",
        dexNumber: 157,
        nameTh: "บาคุฟูน",
        nameEn: "Typhlosion",
        typeId: "fire",
        height: "1.7 m",
        weight: "79.5 kg",
        ability: "Blaze (ไฟลุกโชน)",
        description: "สร้างม่านควันไฟและความร้อนสะสมไว้รอบตัว เมื่อบันดาลโทสะจะระเบิดเปลวไฟเผาผลาญทุกอย่างจนไหม้เกรียม",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/157.png",
      },
      {
        id: "torchic",
        dexNumber: 255,
        nameTh: "อาจาโม",
        nameEn: "Torchic",
        typeId: "fire",
        height: "0.4 m",
        weight: "2.5 kg",
        ability: "Blaze (ไฟลุกโชน)",
        description: "ภายในร่างกายมีถุงเพลิงที่เผาไหม้อยู่ตลอดเวลา เมื่อกอดจะสัมผัสได้ถึงความอบอุ่น สามารถพ่นลูกไฟได้",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/255.png",
      },
      {
        id: "combusken",
        dexNumber: 256,
        nameTh: "วากาชาโม",
        nameEn: "Combusken",
        typeId: "fire",
        height: "0.9 m",
        weight: "19.5 kg",
        ability: "Blaze (ไฟลุกโชน)",
        description: "ฝึกฝนพลังเตะอย่างหนักหน่วงด้วยการวิ่งบนทุ่งหญ้าและภูเขา เตะได้เร็วถึง 10 ครั้งต่อวินาที",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/256.png",
      },
      {
        id: "blaziken",
        dexNumber: 257,
        nameTh: "บาชาโม",
        nameEn: "Blaziken",
        typeId: "fire",
        height: "1.9 m",
        weight: "52.0 kg",
        ability: "Blaze (ไฟลุกโชน)",
        description: "สามารถกระโดดข้ามตึกสูง 30 ชั้นได้สบายๆ ข้อมือมีเปลวไฟลุกโชนเวลาชกปล่อยหมัดเพลิง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/257.png",
      },
      {
        id: "vulpix",
        dexNumber: 37,
        nameTh: "โรกอน",
        nameEn: "Vulpix",
        typeId: "fire",
        height: "0.6 m",
        weight: "9.9 kg",
        ability: "Flash Fire (ไฟลุกติด)",
        description: "เมื่อแรกเกิดมีหางสีขาวเพียงหางเดียว เมื่อเติบโตหางจะแยกออกเป็น 6 หางที่สวยงามและนุ่มฟู",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png",
      },
    ],
  },
  {
    id: "water",
    nameTh: "น้ำ",
    nameEn: "Water",
    icon: "💧",
    colorClass: "text-blue-400",
    bgClass: "bg-blue-600/20 border-blue-500/40 text-blue-300",
    badgeClass: "bg-blue-600 text-white",
    pokemon: [
      {
        id: "totodile",
        dexNumber: 158,
        nameTh: "วานิโนโกะ",
        nameEn: "Totodile",
        typeId: "water",
        height: "0.6 m",
        weight: "9.5 kg",
        ability: "Torrent (พลังน้ำหลาก)",
        description: "โปเกมอนจระเข้ตัวเล็กแต่มีขากรรไกรที่แข็งแกร่ง มีนิสัยขี้เล่นและชอบกัดสิ่งของต่างๆ เพื่อทดสอบแรง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/158.png",
      },
      {
        id: "squirtle",
        dexNumber: 7,
        nameTh: "เซนิกาเมะ",
        nameEn: "Squirtle",
        typeId: "water",
        height: "0.5 m",
        weight: "9.0 kg",
        ability: "Torrent (พลังน้ำหลาก)",
        description: "กระดองที่กลมมนและมีร่องช่วยลดแรงต้านของน้ำ ทำให้ว่ายน้ำได้อย่างรวดเร็วและพ่นน้ำโฟมได้อย่างแม่นยำ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
      },
      {
        id: "wartortle",
        dexNumber: 8,
        nameTh: "คาเมล",
        nameEn: "Wartortle",
        typeId: "water",
        height: "1.0 m",
        weight: "22.5 kg",
        ability: "Torrent (พลังน้ำหลาก)",
        description: "หางขนาดใหญ่มีขนหนานุ่มที่สวยงาม เป็นสัญลักษณ์ของการมีอายุยืนยาว นิยมเลี้ยงเป็นสัตว์นำโชค",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png",
      },
      {
        id: "blastoise",
        dexNumber: 9,
        nameTh: "คาเม็กซ์",
        nameEn: "Blastoise",
        typeId: "water",
        height: "1.6 m",
        weight: "85.5 kg",
        ability: "Torrent (พลังน้ำหลาก)",
        description: "มีปืนใหญ่แรงดันน้ำ 2 กระบอกติดตั้งบนกระดอง สามารถยิงกระแสน้ำแรงดันสูงเจาะทะลุแผ่นเหล็กหนาได้",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png",
      },
      {
        id: "psyduck",
        dexNumber: 54,
        nameTh: "โคดั๊ก",
        nameEn: "Psyduck",
        typeId: "water",
        height: "0.8 m",
        weight: "19.6 kg",
        ability: "Damp (ความชื้น)",
        description: "มักจะปวดหัวอยู่ตลอดเวลา เมื่ออาการปวดศีรษะรุนแรงถึงขีดสุด จะปลดปล่อยพลังจิตอันมหาศาลออกมา",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png",
      },
      {
        id: "kingler",
        dexNumber: 99,
        nameTh: "คิงเกล",
        nameEn: "Kingler",
        typeId: "water",
        height: "1.3 m",
        weight: "60.0 kg",
        ability: "Hyper Cutter (กรรไกรยักษ์)",
        description: "ก้ามข้างหนึ่งพัฒนาจนมีขนาดใหญ่โตมโหฬาร มีแรงหนีบสูงถึง 10,000 แรงม้า แต่หนักจนเคลื่อนไหวยาก",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png",
      },
      {
        id: "magikarp",
        dexNumber: 129,
        nameTh: "คอยคิง",
        nameEn: "Magikarp",
        typeId: "water",
        height: "0.9 m",
        weight: "10.0 kg",
        ability: "Swift Swim (ว่ายน้ำรวดเร็ว)",
        description: "โปเกมอนที่อ่อนแอและน่าสงสาร ทำได้เพียงกระโดดดิ้นไปมาบนผิวน้ำ แต่มีความอึดทนทานสูงในทุกสภาพน้ำ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png",
      },
      {
        id: "lapras",
        dexNumber: 131,
        nameTh: "ลาพลาส",
        nameEn: "Lapras",
        typeId: "water",
        height: "2.5 m",
        weight: "220.0 kg",
        ability: "Water Absorb (ดูดซับน้ำ)",
        description: "โปเกมอนใจดีและฉลาด เข้าใจภาษามนุษย์ ชอบให้คนนั่งบนหลังว่ายข้ามมหาสมุทร มีเสียงร้องที่ไพเราะ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png",
      },
      {
        id: "croconaw",
        dexNumber: 159,
        nameTh: "วานิริก้า",
        nameEn: "Croconaw",
        typeId: "water",
        height: "1.1 m",
        weight: "25.0 kg",
        ability: "Torrent (พลังน้ำหลาก)",
        description: "ฟันที่งอกออกมาพร้อมงอกใหม่ตลอดเวลา เมื่อกัดเหยื่อแล้วจะไม่ยอมปล่อยจนกว่าฟันจะหลุด",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/159.png",
      },
      {
        id: "carvanha",
        dexNumber: 318,
        nameTh: "คาร์วาน่า",
        nameEn: "Carvanha",
        typeId: "water",
        height: "0.8 m",
        weight: "20.8 kg",
        ability: "Rough Skin (ผิวหยาบ)",
        description: "อาศัยรวมกันเป็นฝูงในแม่น้ำป่าดิบชื้น ฟันแหลมคมสามารถฉีกกระชากเรือไม้ให้พังพินาศได้ในพริบตา",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/318.png",
      },
    ],
  },
  {
    id: "grass",
    nameTh: "พืช",
    nameEn: "Grass",
    icon: "🍃",
    colorClass: "text-emerald-400",
    bgClass: "bg-emerald-600/20 border-emerald-500/40 text-emerald-300",
    badgeClass: "bg-emerald-600 text-white",
    pokemon: [
      {
        id: "bulbasaur",
        dexNumber: 1,
        nameTh: "ฟุชิกิดาเนะ",
        nameEn: "Bulbasaur",
        typeId: "grass",
        height: "0.7 m",
        weight: "6.9 kg",
        ability: "Overgrow (พืชเติบใหญ่)",
        description: "มีหัวพืชฝังอยู่บนหลังตั้งแต่แรกเกิด พืชนี้จะค่อยๆ เติบโตขึ้นพร้อมกับขนาดตัวของฟุชิกิดาเนะ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
      },
      {
        id: "ivysaur",
        dexNumber: 2,
        nameTh: "ฟุชิกิโซ",
        nameEn: "Ivysaur",
        typeId: "grass",
        height: "1.0 m",
        weight: "13.0 kg",
        ability: "Overgrow (พืชเติบใหญ่)",
        description: "เมื่อดอกไม้ตูมบนหลังเริ่มบาน จะส่งกลิ่นหอมหวานและเป็นสัญญาณบ่งบอกว่าจะวิวัฒนาการในไม่ช้า",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png",
      },
      {
        id: "venusaur",
        dexNumber: 3,
        nameTh: "ฟุชิกิบานะ",
        nameEn: "Venusaur",
        typeId: "grass",
        height: "2.0 m",
        weight: "100.0 kg",
        ability: "Overgrow (พืชเติบใหญ่)",
        description: "ดอกไม้บานสะพรั่งบนหลังช่วยดูดซับพลังงานจากแสงอาทิตย์ กลิ่นหอมสงบช่วยปลอบประโลมจิตใจของสิ่งมีชีวิตรอบข้าง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png",
      },
      {
        id: "chikorita",
        dexNumber: 152,
        nameTh: "ชิโคริต้า",
        nameEn: "Chikorita",
        typeId: "grass",
        height: "0.9 m",
        weight: "6.4 kg",
        ability: "Overgrow (พืชเติบใหญ่)",
        description: "ใบไม้บนศีรษะสามารถวัดอุณหภูมิและความชื้นในอากาศได้ อีกทั้งยังปล่อยกลิ่นหอมสดชื่นช่วยคลายความตึงเครียด",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/152.png",
      },
      {
        id: "bayleef",
        dexNumber: 153,
        nameTh: "เบย์ลีฟ",
        nameEn: "Bayleef",
        typeId: "grass",
        height: "1.2 m",
        weight: "15.8 kg",
        ability: "Overgrow (พืชเติบใหญ่)",
        description: "ใบไม้รูปวงแหวนรอบคอปล่อยกลิ่นหอมเผ็ดร้อนที่ช่วยกระตุ้นเรี่ยวแรงและฟื้นฟูพลังกายแก่ผู้ที่สูดดม",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/153.png",
      },
      {
        id: "meganium",
        dexNumber: 154,
        nameTh: "เมกานิอุม",
        nameEn: "Meganium",
        typeId: "grass",
        height: "1.8 m",
        weight: "100.5 kg",
        ability: "Overgrow (พืชเติบใหญ่)",
        description: "ลมหายใจของเมกานิอุมมีพลังวิเศษที่สามารถฟื้นฟูต้นไม้ใบหญ้าที่แห้งเหี่ยวให้กลับมาเขียวชอุ่มมีชีวิตชีวา",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/154.png",
      },
      {
        id: "treecko",
        dexNumber: 252,
        nameTh: "คิโมริ",
        nameEn: "Treecko",
        typeId: "grass",
        height: "0.5 m",
        weight: "5.0 kg",
        ability: "Overgrow (พืชเติบใหญ่)",
        description: "ฝ่าเท้ามีหนามเล็กๆ นับไม่ถ้วน ทำให้สามารถไต่ผนังและเพดานแนวตั้งได้อย่างคล่องแคล่วว่องไว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/252.png",
      },
      {
        id: "grovyle",
        dexNumber: 253,
        nameTh: "จุปโทิล",
        nameEn: "Grovyle",
        typeId: "grass",
        height: "0.9 m",
        weight: "21.6 kg",
        ability: "Overgrow (พืชเติบใหญ่)",
        description: "กล้ามเนื้อขาแข็งแกร่งเป็นเลิศ กระโดดข้ามกิ่งไม้ในป่าใหญ่ได้อย่างรวดเร็วจนมองตามแทบไม่ทัน",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/253.png",
      },
      {
        id: "sceptile",
        dexNumber: 254,
        nameTh: "จูไคน์",
        nameEn: "Sceptile",
        typeId: "grass",
        height: "1.7 m",
        weight: "52.2 kg",
        ability: "Overgrow (พืชเติบใหญ่)",
        description: "ใบไม้คมกริบที่งอกบนแขนสามารถตัดต้นไม้ใหญ่ให้ขาดครึ่งได้ ดูแลรักษาต้นไม้ในป่าอย่างทะนุถนอม",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/254.png",
      },
      {
        id: "exeggutor",
        dexNumber: 103,
        nameTh: "นัซซี่",
        nameEn: "Exeggutor",
        typeId: "grass",
        height: "2.0 m",
        weight: "120.0 kg",
        ability: "Chlorophyll (สังเคราะห์แสง)",
        description: "ใบหน้าทั้งสามมีความคิดเป็นของตนเองแต่เข้ากันได้ดี เมื่อหัวหลุดตกลงสู่พื้นจะรวมกลุ่มเกิดเป็นทามะทามะ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png",
      },
    ],
  },
  {
    id: "electric",
    nameTh: "ไฟฟ้า",
    nameEn: "Electric",
    icon: "⚡",
    colorClass: "text-amber-400",
    bgClass: "bg-amber-500/20 border-amber-400/40 text-amber-300",
    badgeClass: "bg-amber-500 text-slate-950 font-bold",
    pokemon: [
      {
        id: "pikachu",
        dexNumber: 25,
        nameTh: "พิคาชู",
        nameEn: "Pikachu",
        typeId: "electric",
        height: "0.4 m",
        weight: "6.0 kg",
        ability: "Static (ไฟฟ้าสถิต)",
        description: "ถุงแก้มสีแดงทั้งสองข้างสามารถกักเก็บกระแสไฟฟ้าได้ เมื่อรู้สึกถึงอันตรายจะปล่อยกระแสไฟฟ้าช็อตใส่ศัตรู",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
      },
      {
        id: "raichu",
        dexNumber: 26,
        nameTh: "ไรชู",
        nameEn: "Raichu",
        typeId: "electric",
        height: "0.8 m",
        weight: "30.0 kg",
        ability: "Static (ไฟฟ้าสถิต)",
        description: "หางยาวทำหน้าที่เป็นสายดินเพื่อป้องกันไม่ให้กระแสไฟฟ้าแรงสูงทำร้ายร่างกายตัวเอง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png",
      },
      {
        id: "magnemite",
        dexNumber: 81,
        nameTh: "คอยล์",
        nameEn: "Magnemite",
        typeId: "electric",
        height: "0.3 m",
        weight: "6.0 kg",
        ability: "Magnet Pull (แรงดึงดูดแม่เหล็ก)",
        description: "ปล่อยคลื่นแม่เหล็กไฟฟ้าออกจากปลายแม่เหล็กทั้งสองข้างเพื่อลอยตัวในอากาศ ดูดซับไฟฟ้าจากเสาไฟฟ้า",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png",
      },
      {
        id: "magneton",
        dexNumber: 82,
        nameTh: "แรร์คอยล์",
        nameEn: "Magneton",
        typeId: "electric",
        height: "1.0 m",
        weight: "60.0 kg",
        ability: "Magnet Pull (แรงดึงดูดแม่เหล็ก)",
        description: "เกิดจากการรวมตัวของคอยล์ 3 ตัว ปล่อยคลื่นวิทยุและสนามแม่เหล็กแรงสูงจนทำให้อุปกรณ์อิเล็กทรอนิกส์ขัดข้อง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png",
      },
      {
        id: "electabuzz",
        dexNumber: 125,
        nameTh: "เอเลบู",
        nameEn: "Electabuzz",
        typeId: "electric",
        height: "1.1 m",
        weight: "30.0 kg",
        ability: "Static (ไฟฟ้าสถิต)",
        description: "ชอบกินกระแสไฟฟ้า มักจะปรากฏตัวใกล้โรงไฟฟ้า เมื่อเกิดพายุฟ้าคะนองจะแข่งกันปีนขึ้นที่สูงเพื่อรับฟ้าผ่า",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png",
      },
      {
        id: "jolteon",
        dexNumber: 135,
        nameTh: "ซันเดอร์ส",
        nameEn: "Jolteon",
        typeId: "electric",
        height: "0.8 m",
        weight: "24.5 kg",
        ability: "Volt Absorb (ดูดซับไฟฟ้า)",
        description: "ขนแหลมคมทั่วตัวแปรสภาพเป็นเข็มประจุไฟฟ้า สามารถยิงเข็มกระแสไฟฟ้า 10,000 โวลต์โจมตีระยะไกลได้",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png",
      },
      {
        id: "zapdos",
        dexNumber: 145,
        nameTh: "ซันเดอร์",
        nameEn: "Zapdos",
        typeId: "electric",
        height: "1.6 m",
        weight: "52.6 kg",
        ability: "Pressure (แรงกดดัน)",
        description: "โปเกมอนนกในตำนานที่ควบคุมสายฟ้า เมื่อกระพือปีกจะก่อให้เกิดเสียงฟ้าร้องคำรามกึกก้องไปทั่วสารทิศ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png",
      },
      {
        id: "mareep",
        dexNumber: 179,
        nameTh: "เมรีป",
        nameEn: "Mareep",
        typeId: "electric",
        height: "0.6 m",
        weight: "7.8 kg",
        ability: "Static (ไฟฟ้าสถิต)",
        description: "ขนแกะนุ่มฟูกักเก็บไฟฟ้าสถิตเอาไว้ เมื่อประจุไฟฟ้าเต็มดวงไฟที่ปลายหางจะส่องแสงสว่างไสว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/179.png",
      },
      {
        id: "flaaffy",
        dexNumber: 180,
        nameTh: "โมโคโค",
        nameEn: "Flaaffy",
        typeId: "electric",
        height: "0.8 m",
        weight: "13.3 kg",
        ability: "Static (ไฟฟ้าสถิต)",
        description: "ผิวหนังยางกันไฟฟ้าช่วยปกป้องตัวเองจากไฟฟ้าสถิตที่สะสมอยู่ในขน ปลายหางส่องแสงนำทางยามค่ำคืน",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/180.png",
      },
      {
        id: "ampharos",
        dexNumber: 181,
        nameTh: "เด็นริว",
        nameEn: "Ampharos",
        typeId: "electric",
        height: "1.4 m",
        weight: "61.5 kg",
        ability: "Static (ไฟฟ้าสถิต)",
        description: "แสงสว่างจากปลายหางสามารถมองเห็นได้ไกลจากอวกาศ ในอดีตผู้คนใช้แสงของเด็นริวเป็นประภาคารนำทางเรือ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/181.png",
      },
    ],
  },
  {
    id: "ice",
    nameTh: "น้ำแข็ง",
    nameEn: "Ice",
    icon: "❄️",
    colorClass: "text-cyan-300",
    bgClass: "bg-cyan-600/20 border-cyan-400/40 text-cyan-300",
    badgeClass: "bg-cyan-600 text-white",
    pokemon: [
      {
        id: "jynx",
        dexNumber: 124,
        nameTh: "รูจูลา",
        nameEn: "Jynx",
        typeId: "ice",
        height: "1.4 m",
        weight: "40.6 kg",
        ability: "Oblivious (ไม่แยแส)",
        description: "โยกย้ายสะโพกไปมาตามจังหวะดนตรีที่น่าหลงใหล ผู้ที่พบเห็นมักจะเผลอเต้นตามไปด้วยโดยไม่รู้ตัว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png",
      },
      {
        id: "articuno",
        dexNumber: 144,
        nameTh: "ฟรีเซอร์",
        nameEn: "Articuno",
        typeId: "ice",
        height: "1.7 m",
        weight: "55.4 kg",
        ability: "Pressure (แรงกดดัน)",
        description: "โปเกมอนนกในตำนานที่มีปีกงดงามดั่งผลึกน้ำแข็ง บินอยู่เหนือยอดเขาหิมะและช่วยเหลือนักปีนเขาที่หลงทาง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png",
      },
      {
        id: "swinub",
        dexNumber: 220,
        nameTh: "ยูคิฮิวาระ",
        nameEn: "Swinub",
        typeId: "ice",
        height: "0.4 m",
        weight: "6.5 kg",
        ability: "Oblivious (ไม่แยแส)",
        description: "ใช้ปลายจมูกขุดคุ้ยดินเพื่อหาอาหารใต้หิมะ มีประสาทดมกลิ่นอันยอดเยี่ยม สามารถหากล้วยไม้ป่าและเห็ดได้",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/220.png",
      },
      {
        id: "piloswine",
        dexNumber: 221,
        nameTh: "อิโนมู",
        nameEn: "Piloswine",
        typeId: "ice",
        height: "1.1 m",
        weight: "55.8 kg",
        ability: "Oblivious (ไม่แยแส)",
        description: "ขนยาวรุงรังบดบังดวงตา ทำให้มองไม่เห็นทางข้างหน้า จึงอาศัยประสาทหูและจมูกในการรับรู้สภาพแวดล้อม",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/221.png",
      },
      {
        id: "delibird",
        dexNumber: 225,
        nameTh: "เดลิเบิร์ด",
        nameEn: "Delibird",
        typeId: "ice",
        height: "0.9 m",
        weight: "16.0 kg",
        ability: "Vital Spirit (จิตวิญญาณมีชีวิตชีวา)",
        description: "หางที่ม้วนพับเก็บอาหารไว้แจกจ่ายให้แก่ผู้คนหรือโปเกมอนที่ติดอยู่ท่ามกลางพายุหิมะอันเหน็บหนาว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/225.png",
      },
      {
        id: "snorunt",
        dexNumber: 361,
        nameTh: "ยูคิวาราชิ",
        nameEn: "Snorunt",
        typeId: "ice",
        height: "0.7 m",
        weight: "16.8 kg",
        ability: "Inner Focus (มีสมาธิ)",
        description: "อาศัยอยู่ในแถบที่มีหิมะตกหนัก เชื่อกันว่าบ้านใดที่ยูคิวาราชิมาเยือนจะร่ำรวยและมีความเจริญรุ่งเรือง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/361.png",
      },
      {
        id: "glalie",
        dexNumber: 362,
        nameTh: "โอนิโกริ",
        nameEn: "Glalie",
        typeId: "ice",
        height: "1.5 m",
        weight: "256.5 kg",
        ability: "Inner Focus (มีสมาธิ)",
        description: "ร่างกายเป็นก้อนหินที่ถูกหุ้มด้วยเกราะน้ำแข็งแข็งแกร่ง ไม่ละลายแม้จะโดนเปลวไฟ สามารถแช่แข็งความชื้นรอบตัวได้ทันที",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/362.png",
      },
      {
        id: "spheal",
        dexNumber: 363,
        nameTh: "ทามะซาราชิ",
        nameEn: "Spheal",
        typeId: "ice",
        height: "0.8 m",
        weight: "39.5 kg",
        ability: "Thick Fat (ไขมันหนา)",
        description: "ร่างกายกลมดิกคล้ายลูกบอล เคลื่อนที่ด้วยการกลิ้งไปบนแผ่นน้ำแข็งเร็วกว่าการเดิน ปรบมือเสียงดังเวลาร่าเริง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/363.png",
      },
      {
        id: "walrein",
        dexNumber: 365,
        nameTh: "โทโดเซลก้า",
        nameEn: "Walrein",
        typeId: "ice",
        height: "1.4 m",
        weight: "150.6 kg",
        ability: "Thick Fat (ไขมันหนา)",
        description: "เขี้ยวขนาดใหญ่ทรงพลังสามารถทำลายภูเขาน้ำแข็งหนัก 10 ตันให้แตกเป็นเสี่ยงๆ ได้ในคราวเดียว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/365.png",
      },
      {
        id: "glaceon",
        dexNumber: 471,
        nameTh: "กลาเซีย",
        nameEn: "Glaceon",
        typeId: "ice",
        height: "0.8 m",
        weight: "25.9 kg",
        ability: "Snow Cloak (เสื้อคลุมหิมะ)",
        description: "ควบคุมอุณหภูมิร่างกายให้ลดต่ำลงถึง -60 องศาเซลเซียส เปลี่ยนขนทั่วตัวให้กลายเป็นผลึกน้ำแข็งแหลมคม",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/471.png",
      },
    ],
  },
  {
    id: "fighting",
    nameTh: "ต่อสู้",
    nameEn: "Fighting",
    icon: "🥊",
    colorClass: "text-red-500",
    bgClass: "bg-red-700/20 border-red-500/40 text-red-300",
    badgeClass: "bg-red-700 text-white",
    pokemon: [
      {
        id: "mankey",
        dexNumber: 56,
        nameTh: "แมนคีย์",
        nameEn: "Mankey",
        typeId: "fighting",
        height: "0.5 m",
        weight: "28.0 kg",
        ability: "Vital Spirit (จิตวิญญาณมีชีวิตชีวา)",
        description: "อารมณ์ฉุนเฉียวและโกรธง่ายมาก หากสบตาจะวิ่งเข้าใส่และออกหมัดโจมตีอย่างบ้าคลั่งทันที",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png",
      },
      {
        id: "primeape",
        dexNumber: 57,
        nameTh: "โอโคริซารุ",
        nameEn: "Primeape",
        typeId: "fighting",
        height: "1.0 m",
        weight: "32.0 kg",
        ability: "Vital Spirit (จิตวิญญาณมีชีวิตชีวา)",
        description: "ความโกรธสะสมทำให้กล้ามเนื้อตึงแน่นและเพิ่มพละกำลังมหาศาล ไล่ตามศัตรูไปจนสุดหล้าฟ้าเขียว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png",
      },
      {
        id: "machop",
        dexNumber: 66,
        nameTh: "วันริกี",
        nameEn: "Machop",
        typeId: "fighting",
        height: "0.8 m",
        weight: "19.5 kg",
        ability: "Guts (ความกล้าหาญ)",
        description: "แม้ตัวเล็กแต่สามารถยกก้อนหินหนักกว่าตัวเองได้สบายๆ ฝึกยกหินภูเขาทุกวันเพื่อเสริมสร้างความแข็งแกร่ง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png",
      },
      {
        id: "machoke",
        dexNumber: 67,
        nameTh: "โกริกี",
        nameEn: "Machoke",
        typeId: "fighting",
        height: "1.5 m",
        weight: "70.5 kg",
        ability: "Guts (ความกล้าหาญ)",
        description: "เข็มขัดที่คาดเอวช่วยสะกดพลังกล้ามเนื้ออันมหาศาลเอาไว้ มักทำงานช่วยเหลือมนุษย์ในงานก่อสร้างหนัก",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png",
      },
      {
        id: "machamp",
        dexNumber: 68,
        nameTh: "ไคริกี",
        nameEn: "Machamp",
        typeId: "fighting",
        height: "1.6 m",
        weight: "130.0 kg",
        ability: "Guts (ความกล้าหาญ)",
        description: "แขนทั้งสี่ข้างสามารถปล่อยหมัดได้ 1,000 ครั้งในเวลาเพียง 2 วินาที เคลื่อนไหวด้านศิลปะการต่อสู้ได้อย่างช่ำชอง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png",
      },
      {
        id: "hitmonlee",
        dexNumber: 106,
        nameTh: "ซาวามูลาร์",
        nameEn: "Hitmonlee",
        typeId: "fighting",
        height: "1.5 m",
        weight: "49.8 kg",
        ability: "Limber (ยืดหยุ่น)",
        description: "ขาทั้งสองข้างสามารถยืดหดได้คล้ายสปริง เตะคู่ต่อสู้จากระยะไกลได้อย่างรวดเร็วและแม่นยำดั่งสายฟ้าฟาด",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png",
      },
      {
        id: "hitmonchan",
        dexNumber: 107,
        nameTh: "เอบิวาลาร์",
        nameEn: "Hitmonchan",
        typeId: "fighting",
        height: "1.4 m",
        weight: "50.2 kg",
        ability: "Keen Eye (สายตาเฉียบคม)",
        description: "สปิริตแห่งนักชกมวยสากล หมัดควงสว่านตัดอากาศจนเกิดความร้อน สามารถต่อยทะลุคอนกรีตเสริมเหล็กได้",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png",
      },
      {
        id: "hitmontop",
        dexNumber: 237,
        nameTh: "คาโปเอร่า",
        nameEn: "Hitmontop",
        typeId: "fighting",
        height: "1.4 m",
        weight: "48.0 kg",
        ability: "Intimidate (ข่มขวัญ)",
        description: "หมุนตัวด้วยความเร็วสูงคล้ายลูกข่างและปล่อยลูกเตะต่อเนื่อง เป็นการผสมผสานการโจมตีและการป้องกันที่ไร้ช่องโหว่",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/237.png",
      },
      {
        id: "hariyama",
        dexNumber: 297,
        nameTh: "ฮาริยามะ",
        nameEn: "Hariyama",
        typeId: "fighting",
        height: "2.3 m",
        weight: "253.8 kg",
        ability: "Thick Fat (ไขมันหนา)",
        description: "ฝ่ามือตบซูโม่สามารถผลักรถบรรทุก 10 ตันให้กระเด็นถอยหลังได้ มีความอดทนต่อการโจมตีทางกายภาพสูงเป็นพิเศษ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/297.png",
      },
      {
        id: "lucario",
        dexNumber: 448,
        nameTh: "ลูคาริโอ",
        nameEn: "Lucario",
        typeId: "fighting",
        height: "1.2 m",
        weight: "54.0 kg",
        ability: "Steadfast (แน่วแน่)",
        description: "สัมผัสคลื่นออร่าของสิ่งมีชีวิตได้รอบทิศทาง สามารถอ่านใจและการเคลื่อนไหวล่วงหน้าของคู่ต่อสู้ได้อย่างสมบูรณ์",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png",
      },
    ],
  },
  {
    id: "poison",
    nameTh: "พิษ",
    nameEn: "Poison",
    icon: "☠️",
    colorClass: "text-purple-400",
    bgClass: "bg-purple-600/20 border-purple-500/40 text-purple-300",
    badgeClass: "bg-purple-600 text-white",
    pokemon: [
      {
        id: "beedrill",
        dexNumber: 15,
        nameTh: "บีดริล",
        nameEn: "Beedrill",
        typeId: "poison",
        height: "1.0 m",
        weight: "29.5 kg",
        ability: "Swarm (ฝูงแมลง)",
        description: "เหล็กในพิษแหลมคมที่แขนทั้งสองข้างและก้น บินเข้าจู่โจมศัตรูเป็นฝูงด้วยความเร็วสูงเพื่อปกป้องรัง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png",
      },
      {
        id: "ekans",
        dexNumber: 23,
        nameTh: "อาโบ",
        nameEn: "Ekans",
        typeId: "poison",
        height: "2.0 m",
        weight: "6.9 kg",
        ability: "Intimidate (ข่มขวัญ)",
        description: "เคลื่อนที่ในพงหญ้าเงียบเชียบ สามารถปลดขากรรไกรกลืนกินเหยื่อที่มีขนาดใหญ่กว่าหัวตนเองได้ทั้งตัว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png",
      },
      {
        id: "arbok",
        dexNumber: 24,
        nameTh: "อาบ็อก",
        nameEn: "Arbok",
        typeId: "poison",
        height: "3.5 m",
        weight: "65.0 kg",
        ability: "Intimidate (ข่มขวัญ)",
        description: "ลวดลายหน้าตาน่าสะพรึงกลัวบนแผงคอช่วยข่มขวัญคู่ต่อสู้ให้หยุดนิ่ง ก่อนจะรัดเหยื่อด้วยลำตัวอันทรงพลัง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png",
      },
      {
        id: "nidoran-f",
        dexNumber: 29,
        nameTh: "นิโดรันเพศเมีย",
        nameEn: "Nidoran♀",
        typeId: "poison",
        height: "0.4 m",
        weight: "7.0 kg",
        ability: "Poison Point (จุดพิษ)",
        description: "แม้จะมีขนาดเล็กและดูน่ารัก แต่หนามตามลำตัวซ่อนพิษร้ายแรงไว้เพื่อป้องกันตัวจากอันตรายรอบตัว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png",
      },
      {
        id: "nidoran-m",
        dexNumber: 32,
        nameTh: "นิโดรันเพศผู้",
        nameEn: "Nidoran♂",
        typeId: "poison",
        height: "0.5 m",
        weight: "9.0 kg",
        ability: "Poison Point (จุดพิษ)",
        description: "เขามีพิษบนหน้าผากใช้สำหรับพุ่งชนและขับพิษออกมาเมื่อรับรู้ถึงความโกรธหรือศัตรูในระยะประชิด",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png",
      },
      {
        id: "zubat",
        dexNumber: 41,
        nameTh: "ซูแบท",
        nameEn: "Zubat",
        typeId: "poison",
        height: "0.8 m",
        weight: "7.5 kg",
        ability: "Inner Focus (มีสมาธิ)",
        description: "ไม่มีดวงตา อาศัยอยู่ในถ้ำมืดสนิท ปล่อยคลื่นเสียงสะท้อนจากปากเพื่อตรวจจับทิศทางและสิ่งกีดขวาง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png",
      },
      {
        id: "golbat",
        dexNumber: 42,
        nameTh: "โกลแบท",
        nameEn: "Golbat",
        typeId: "poison",
        height: "1.6 m",
        weight: "55.0 kg",
        ability: "Inner Focus (มีสมาธิ)",
        description: "ปากขนาดใหญ่มีฟันแหลมคม สามารถดูดเลือดเหยื่อได้มากกว่า 300 ซีซีในครั้งเดียวจนตัวหนักบินไม่ไหว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png",
      },
      {
        id: "koffing",
        dexNumber: 109,
        nameTh: "โดกัส",
        nameEn: "Koffing",
        typeId: "poison",
        height: "0.6 m",
        weight: "1.0 kg",
        ability: "Levitate (ลอยตัว)",
        description: "ภายในร่างกายที่บางเบาบรรจุแก๊สพิษและสารระเบิด ลอยล่องตามสายลมและปล่อยกลิ่นฉุนรุนแรง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png",
      },
      {
        id: "weezing",
        dexNumber: 110,
        nameTh: "มาทาโดกัส",
        nameEn: "Weezing",
        typeId: "poison",
        height: "1.2 m",
        weight: "9.5 kg",
        ability: "Levitate (ลอยตัว)",
        description: "หัวทั้งสองผสมผสานแก๊สพิษชนิดต่างๆ เข้าด้วยกัน สร้างกลิ่นเหม็นที่สามารถทำให้คนสลบได้ทันที",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png",
      },
      {
        id: "crobat",
        dexNumber: 169,
        nameTh: "โครแบท",
        nameEn: "Crobat",
        typeId: "poison",
        height: "1.8 m",
        weight: "75.0 kg",
        ability: "Inner Focus (มีสมาธิ)",
        description: "ปีกทั้งสี่ข้างช่วยให้บินได้อย่างเงียบกริบและรวดเร็วเป็นพิเศษ บินโฉบเข้าหาเหยื่อในความมืดโดยไร้ร่องรอย",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/169.png",
      },
    ],
  },
  {
    id: "ground",
    nameTh: "พื้นดิน",
    nameEn: "Ground",
    icon: "⛰️",
    colorClass: "text-amber-500",
    bgClass: "bg-amber-700/20 border-amber-600/40 text-amber-200",
    badgeClass: "bg-amber-700 text-white",
    pokemon: [
      {
        id: "sandshrew",
        dexNumber: 27,
        nameTh: "แซนด์",
        nameEn: "Sandshrew",
        typeId: "ground",
        height: "0.6 m",
        weight: "12.0 kg",
        ability: "Sand Veil (ม่านทราย)",
        description: "ขุดโพรงลึกใต้ดินในทะเลทราย เมื่อถูกโจมตีจะม้วนตัวเป็นลูกบอลกลมแข็งแกร่งเพื่อสะท้อนการโจมตี",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png",
      },
      {
        id: "sandslash",
        dexNumber: 28,
        nameTh: "แซนด์แพน",
        nameEn: "Sandslash",
        typeId: "ground",
        height: "1.0 m",
        weight: "29.5 kg",
        ability: "Sand Veil (ม่านทราย)",
        description: "หนามแหลมคมบนหลังและกรงเล็บขนาดใหญ่ใช้สำหรับขุดเจาะและตะปบศัตรู ก่อพายุทรายกำบังสายตา",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png",
      },
      {
        id: "diglett",
        dexNumber: 50,
        nameTh: "ดิกด้า",
        nameEn: "Diglett",
        typeId: "ground",
        height: "0.2 m",
        weight: "0.8 kg",
        ability: "Sand Veil (ม่านทราย)",
        description: "อาศัยอยู่ใต้ดินตื้นๆ กินรากไม้เป็นอาหาร ลำตัวที่โผล่พ้นผืนดินเป็นเพียงส่วนหัว ยังไม่มีใครเคยเห็นร่างกายส่วนล่าง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png",
      },
      {
        id: "dugtrio",
        dexNumber: 51,
        nameTh: "ดักทริโอ",
        nameEn: "Dugtrio",
        typeId: "ground",
        height: "0.7 m",
        weight: "33.3 kg",
        ability: "Sand Veil (ม่านทราย)",
        description: "ดิกด้าสามตัวร่วมมือกันขุดดินลงไปลึกถึง 100 กิโลเมตร ก่อให้เกิดแผ่นดินไหวขนาดเล็กเมื่อขุดเจาะพร้อมกัน",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png",
      },
      {
        id: "cubone",
        dexNumber: 104,
        nameTh: "คาราระ",
        nameEn: "Cubone",
        typeId: "ground",
        height: "0.4 m",
        weight: "6.5 kg",
        ability: "Rock Head (หัวหิน)",
        description: "สวมกะโหลกศีรษะของแม่ที่จากไปไว้บนหัวเสมอ เมื่อร้องไห้ด้วยความคิดถึง เสียงจะสะท้อนก้องในกะโหลกอย่างเศร้าสร้อย",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png",
      },
      {
        id: "marowak",
        dexNumber: 105,
        nameTh: "การาการา",
        nameEn: "Marowak",
        typeId: "ground",
        height: "1.0 m",
        weight: "45.0 kg",
        ability: "Rock Head (หัวหิน)",
        description: "ก้าวข้ามความเศร้าโศกและเติบโตอย่างเข้มแข็ง เหวี่ยงท่อนกระดูกในมือดั่งบูมเมอแรงโจมตีเป้าหมายอย่างแม่นยำ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png",
      },
      {
        id: "rhyhorn",
        dexNumber: 111,
        nameTh: "ไซฮอร์น",
        nameEn: "Rhyhorn",
        typeId: "ground",
        height: "1.0 m",
        weight: "115.0 kg",
        ability: "Lightning Rod (สายล่อฟ้า)",
        description: "วิ่งพุ่งชนตรงไปข้างหน้าด้วยกำลังมหาศาล สมองมีขนาดเล็กจึงมักจะลืมว่ากำลังวิ่งไล่ชนอะไรอยู่ระหว่างทาง",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png",
      },
      {
        id: "rhydon",
        dexNumber: 112,
        nameTh: "ไซดอน",
        nameEn: "Rhydon",
        typeId: "ground",
        height: "1.9 m",
        weight: "120.0 kg",
        ability: "Lightning Rod (สายล่อฟ้า)",
        description: "เขาสว่านบนจมูกสามารถหมุนเจาะทะลุหินผาและเพชรได้ ผิวหนังหนาเหมือนเกราะทนความร้อนจากลาวาภูเขาไฟ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png",
      },
      {
        id: "wooper",
        dexNumber: 194,
        nameTh: "อูพาร์",
        nameEn: "Wooper",
        typeId: "ground",
        height: "0.4 m",
        weight: "8.5 kg",
        ability: "Damp (ความชื้น)",
        description: "อาศัยอยู่ในน้ำเย็น เมื่อขึ้นมาบนบกจะเคลือบผิวหนังด้วยเมือกพิษเพื่อรักษาความชุ่มชื้นและป้องกันศัตรู",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/194.png",
      },
      {
        id: "quagsire",
        dexNumber: 195,
        nameTh: "นูโอ",
        nameEn: "Quagsire",
        typeId: "ground",
        height: "1.4 m",
        weight: "75.0 kg",
        ability: "Damp (ความชื้น)",
        description: "มีนิสัยสบายๆ ไม่ค่อยใส่ใจเรื่องรอบตัว มักจะอ้าปากรอให้เหยื่อว่ายเข้ามาในปากเองตามแม่น้ำ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/195.png",
      },
    ],
  },
  {
    id: "flying",
    nameTh: "บิน",
    nameEn: "Flying",
    icon: "🪽",
    colorClass: "text-sky-400",
    bgClass: "bg-sky-600/20 border-sky-400/40 text-sky-200",
    badgeClass: "bg-sky-500 text-slate-950 font-bold",
    pokemon: [
      {
        id: "pidgey",
        dexNumber: 16,
        nameTh: "ป็อปโปะ",
        nameEn: "Pidgey",
        typeId: "flying",
        height: "0.3 m",
        weight: "1.8 kg",
        ability: "Keen Eye (สายตาเฉียบคม)",
        description: "มีทิศทางการรับรู้ที่ยอดเยี่ยม ไม่ว่าจะบินไปไกลแค่ไหนก็สามารถบินกลับรังเดิมได้อย่างแม่นยำ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png",
      },
      {
        id: "pidgeotto",
        dexNumber: 17,
        nameTh: "พิเจียน",
        nameEn: "Pidgeotto",
        typeId: "flying",
        height: "1.1 m",
        weight: "30.0 kg",
        ability: "Keen Eye (สายตาเฉียบคม)",
        description: "บินวนเวียนอยู่บนท้องฟ้าเพื่อตรวจตรารัง สายตาคมกริบสามารถมองเห็นเหยื่อบนพื้นหญ้าจากความสูงนับร้อยเมตร",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png",
      },
      {
        id: "pidgeot",
        dexNumber: 18,
        nameTh: "พีเจียต",
        nameEn: "Pidgeot",
        typeId: "flying",
        height: "1.5 m",
        weight: "39.5 kg",
        ability: "Keen Eye (สายตาเฉียบคม)",
        description: "กางปีกขนาดใหญ่งดงามและบินด้วยความเร็วสูงถึง มัค 2 กรงเล็บทรงพลังใช้ตะครุบคอยคิงขึ้นมาจากน้ำ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png",
      },
      {
        id: "spearow",
        dexNumber: 21,
        nameTh: "โอนิสึสึเมะ",
        nameEn: "Spearow",
        typeId: "flying",
        height: "0.3 m",
        weight: "2.0 kg",
        ability: "Keen Eye (สายตาเฉียบคม)",
        description: "กระพือปีกสั้นๆ บินไปมาด้วยความเร็ว ส่งเสียงร้องแหลมสูงเพื่อเตือนภัยและเรียกเพื่อนฝูงมาช่วยกันรุมจิก",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png",
      },
      {
        id: "fearow",
        dexNumber: 22,
        nameTh: "โอนิเดริล",
        nameEn: "Fearow",
        typeId: "flying",
        height: "1.2 m",
        weight: "38.0 kg",
        ability: "Keen Eye (สายตาเฉียบคม)",
        description: "คอยาวและจงอยปากยาวแหลมคม บินร่อนกลางเวหาได้ทั้งวันโดยไม่ต้องพักผ่อนเพื่อมองหาเหยื่อ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png",
      },
      {
        id: "doduo",
        dexNumber: 84,
        nameTh: "โดโด",
        nameEn: "Doduo",
        typeId: "flying",
        height: "1.4 m",
        weight: "39.2 kg",
        ability: "Run Away (หลบหนี)",
        description: "นกสองหัวที่ไม่สามารถบินได้แต่วิ่งได้เร็วถึง 100 กม./ชม. หัวทั้งสองจะผลัดกันนอนหลับเพื่อเฝ้าระวังภัย",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png",
      },
      {
        id: "dodrio",
        dexNumber: 85,
        nameTh: "โดโดริโอ",
        nameEn: "Dodrio",
        typeId: "flying",
        height: "1.8 m",
        weight: "85.2 kg",
        ability: "Run Away (หลบหนี)",
        description: "หัวทั้งสามแสดงออกถึงความสุข ความเศร้า และความโกรธ วิ่งข้ามทุ่งกว้างด้วยความเร็วสูงอย่างไร้คู่เปรียบ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png",
      },
      {
        id: "swablu",
        dexNumber: 333,
        nameTh: "สวาเบลู",
        nameEn: "Swablu",
        typeId: "flying",
        height: "0.4 m",
        weight: "1.2 kg",
        ability: "Natural Cure (รักษาตามธรรมชาติ)",
        description: "ปีกทั้งสองฟูนุ่มดั่งปุยเมฆสีขาว รักความสะอาดมาก หากเห็นสิ่งสกปรกจะใช้ปีกเช็ดทำความสะอาดทันที",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/333.png",
      },
      {
        id: "altaria",
        dexNumber: 334,
        nameTh: "ชิลทาริส",
        nameEn: "Altaria",
        typeId: "flying",
        height: "1.1 m",
        weight: "20.6 kg",
        ability: "Natural Cure (รักษาตามธรรมชาติ)",
        description: "ขับขานบทเพลงโซปราโนอันไพเราะสะกดใจผู้ฟัง ร่อนถลาท่ามกลางหมู่เมฆอย่างสง่างาม",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/334.png",
      },
      {
        id: "starly",
        dexNumber: 396,
        nameTh: "สตาร์ลี",
        nameEn: "Starly",
        typeId: "flying",
        height: "0.3 m",
        weight: "2.0 kg",
        ability: "Keen Eye (สายตาเฉียบคม)",
        description: "อาศัยรวมกันเป็นฝูงใหญ่ในป่าและทุ่งหญ้า เมื่ออยู่ตามลำพังจะมีนิสัยขี้อายและส่งเสียงร้องเบาๆ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/396.png",
      },
    ],
  },
  {
    id: "psychic",
    nameTh: "พลังจิต",
    nameEn: "Psychic",
    icon: "🌀",
    colorClass: "text-rose-400",
    bgClass: "bg-rose-600/20 border-rose-500/40 text-rose-300",
    badgeClass: "bg-rose-600 text-white",
    pokemon: [
      {
        id: "abra",
        dexNumber: 63,
        nameTh: "เคซี",
        nameEn: "Abra",
        typeId: "psychic",
        height: "0.9 m",
        weight: "19.5 kg",
        ability: "Synchronize (ซิงโครไนซ์)",
        description: "นอนหลับพักผ่อนวันละ 18 ชั่วโมง แม้ในขณะหลับยังสามารถใช้พลังจิตเคลื่อนย้ายพริบตา (Teleport) หลบหนีศัตรูได้",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png",
      },
      {
        id: "kadabra",
        dexNumber: 64,
        nameTh: "ยุนเกเลอร์",
        nameEn: "Kadabra",
        typeId: "psychic",
        height: "1.3 m",
        weight: "56.5 kg",
        ability: "Synchronize (ซิงโครไนซ์)",
        description: "ถือช้อนเงินในมือเพื่อช่วยโฟกัสและเพิ่มพลังคลื่นจิต ปล่อยคลื่นอัลฟ่ารบกวนนาฬิกาและเข็มทิศรอบตัว",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png",
      },
      {
        id: "alakazam",
        dexNumber: 65,
        nameTh: "ฟูดิน",
        nameEn: "Alakazam",
        typeId: "psychic",
        height: "1.5 m",
        weight: "48.0 kg",
        ability: "Synchronize (ซิงโครไนซ์)",
        description: "มีไอคิวสูงถึง 5,000 สมองเติบโตอย่างไม่หยุดยั้ง สามารถจดจำทุกเหตุการณ์ที่เกิดขึ้นในชีวิตได้อย่างสมบูรณ์",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png",
      },
      {
        id: "drowzee",
        dexNumber: 96,
        nameTh: "สลีป",
        nameEn: "Drowzee",
        typeId: "psychic",
        height: "1.0 m",
        weight: "32.4 kg",
        ability: "Insomnia (ไม่ยอมนอน)",
        description: "สะกดเหยื่อให้หลับใหลแล้วสูดกินความฝันทางรูจมูก ชอบกินความฝันที่สนุกสนานของเด็กๆ เป็นพิเศษ",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png",
      },
      {
        id: "hypno",
        dexNumber: 97,
        nameTh: "สลีปเปอร์",
        nameEn: "Hypno",
        typeId: "psychic",
        height: "1.6 m",
        weight: "75.6 kg",
        ability: "Insomnia (ไม่ยอมนอน)",
        description: "แกว่งลูกตุ้มลูกดิ่งในมือเป็นจังหวะเพื่อสะกดจิตคู่ต่อสู้ให้ตกอยู่ในภวังค์ความหลับลึกอย่างไม่อาจขัดขืน",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png",
      },
      {
        id: "mr-mime",
        dexNumber: 122,
        nameTh: "บาริยาร์ด",
        nameEn: "Mr. Mime",
        typeId: "psychic",
        height: "1.2 m",
        weight: "54.5 kg",
        ability: "Soundproof (กันเสียง)",
        description: "ผู้เชี่ยวชาญการแสดงละครใบ้ ปล่อยคลื่นความกดอากาศจากปลายนิ้วสร้างกำแพงล่องหนที่แข็งแกร่งดั่งคอนกรีต",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png",
      },
      {
        id: "espeon",
        dexNumber: 196,
        nameTh: "เอฟี",
        nameEn: "Espeon",
        typeId: "psychic",
        height: "0.9 m",
        weight: "26.5 kg",
        ability: "Synchronize (ซิงโครไนซ์)",
        description: "ขนกำมะหยี่นุ่มสัมผัสการเคลื่อนไหวของกระแสลม อัญมณีสีแดงบนหน้าผากจะเปล่งแสงเมื่อทำนายอนาคต",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/196.png",
      },
      {
        id: "unown",
        dexNumber: 201,
        nameTh: "อันโนน",
        nameEn: "Unown",
        typeId: "psychic",
        height: "0.5 m",
        weight: "5.0 kg",
        ability: "Levitate (ลอยตัว)",
        description: "รูปร่างคล้ายตัวอักษรโบราณ อาศัยอยู่ในซากปรักหักพัง เมื่อรวมตัวกันจำนวนมากจะก่อให้เกิดพลังลึกลับมหาศาล",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/201.png",
      },
      {
        id: "wynaut",
        dexNumber: 360,
        nameTh: "โซนาโน",
        nameEn: "Wynaut",
        typeId: "psychic",
        height: "0.6 m",
        weight: "14.0 kg",
        ability: "Shadow Tag (เงามัดร่าง)",
        description: "มีรอยยิ้มเบิกบานอยู่บนใบหน้าเสมอ รวมกลุ่มชนตัวกันในถ้ำเพื่อฝึกฝนความอดทนและสะท้อนการโจมตี",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/360.png",
      },
      {
        id: "mewtwo",
        dexNumber: 150,
        nameTh: "มิวทู",
        nameEn: "Mewtwo",
        typeId: "psychic",
        height: "2.0 m",
        weight: "122.0 kg",
        ability: "Pressure (แรงกดดัน)",
        description: "โปเกมอนที่ถือกำเนิดจากการตัดต่อพันธุกรรมของมิว มีจิตใจเย็นชาและมีพลังจิตต่อสู้ที่รุนแรงที่สุดในโลก",
        imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png",
      },
    ],
  },
];
